---
title: "Series"
---

A sequence $\{a_n\}$ is a list of numbers in a definite order:

$$a_1, a_2, \ ..., a_n, \  ...$$

A sequence converges when the limit of the sequence exists:

\[\lim_{n \rightarrow \infty}{a_n} = a\]

## Examples

- Example 1:

$$
a_n=\frac{n}{n+1}
$$

$$
\frac{1}{2}, \frac{2}{3}, \frac{3}{4}, ..., \frac{i}{i+1}, ...
$$

It converges as:

\[lim_{n \rightarrow \infty}{a_n} = 1\]

- Example 2:

$$a_n=3^n$$

$$3, 9, 27, ..., 3^i, ...$$

It is straightforward that it does not converge (i.e. divergent sequence).

## Convergence of partial sums

A partial sum of a sequence $\{a_n\}$ is defined as:

$$s_n = a_1 + a_2 + ... + a_n$$

If the partial sum $\{s_n\}$ converges to a number $s$, the following inifinite series is convergent and equal to $s$:

\[\sum^{\infty}_{k=1} a_k = \lim_{n \rightarrow \infty}{s_n} = \lim_{n \rightarrow \infty}{(a_1 + a_2 + ... + a_n)} = s \]

Otherwise, $$\sum^{\infty}_{k=1} a_k$$ is divergent.

### Absolute convergence

Series is absolutely convergent if the following converges:

$$\sum^{\infty}_{k=1} |a_k|$$

Absolute convergence is a stronger convergence that implies normal convergence as well.

## Convergence tests

There are tests to check the convergence of a series. Such as ratio test, comparison test, root test, etc.

## Geometric series

A geometric sequence multiplies each position of the sequence by some $r$:

$$\{ar^{n-1}\}^{\infty}_{n=1} = \{a, ar, ar^2, ar^3, ...\}$$

A geometric series adds the numbers of a geometric sequence, such that:

$$\sum^{\infty}_{k=1} ar^{k-1} = \frac{a}{1-r}, \ if \ |r| < 1$$

Therefore, geometric series always converge if $|r| < 1$.

### Example 1


If we have some rational function of some given forms, we can express them as a geometric series and rewrite them as an infinite sum. For instance:

$$\frac{1}{1-x} = 1 + x + x^2 + x^3 + ...$$

Where $a = 1$ and $r=x$. Note that this only holds when $|x| < 1$.


### Example 2

If we have a more complex function as such, where we find a quadratic denominator:

$$
\frac{1}{(1-x)(1-\frac{x}{2})}
$$

We can expand the function into partial fractions:

$$
\frac{1}{(1-x)(1-\frac{x}{2})} = \frac{2}{1-x}+\frac{-1}{1-\frac{x}{2}}
$$

Then we can express each of the fractions as a geometric series:

- $a = 2$ and $r=x$ for first fraction. So we can express it as:

$$\frac{2}{(1-x)} = \sum^{\infty}_{k=0} 2x^k$$

- $a = -1$ and $r = \frac{x}{2}$ for the second fraction. So we can express it as:

$$\frac{-1}{1-\frac{x}{2}} = \sum^{\infty}_{k=0} - \left(\frac{x}{2}\right)^k$$

Then, we can combine them by summing them:

$$
\frac{1}{(1-x)(1-\frac{x}{2})} = \frac{2}{1-x}+\frac{-1}{1-\frac{x}{2}} = \sum^{\infty}_{k=0} 2x^k - \left(\frac{x}{2}\right)^k = \sum^{\infty}_{k=0} \left(2 - \frac{1}{2^k}\right) x^k
$$

In order to do so we must ensure that both fractions are convergent. So:

- For first fraction to be convergent, we need $|r| = |x| < 1$.
- For second fraction to be convergent, we need $|r| = |\frac{x}{2}| < 1$.

Therefore if $|x| < 1$, the geometric expansion above holds.

## Example 3

If we have a complex number $z$, we can rewrite the following:

$$\frac{a}{1 - z} = a + az + az^2 + ... = \sum^{\infty}_{k=1} az^{k-1}$$

For $|z| < 1$.