---
title: "Duality"
---

## Invertibility conditions for $MA(q)$ processes

### MA(q) recap

We have seen moving average process of order $q$, $MA(q)$:

$$
X_t = \beta_0 Z_t + \beta_1 Z_{t-1} + \ ... \ + \beta_q Z_{t-q}
$$
Can be rewritten using backward shift operator:

$$
X_t = (\beta_0 + \beta_1 B + \beta_2 B^2 + ... + \beta_q B^q) Z_t \\
X_t = \beta(B) Z_t
$$

In order a moving average to be invertible, **all complex roots of the polynomial $\beta(B)$ must lie outside of the unit circle where $\beta$ is regarded as a complex variable**.

#### MA(2) example

We have the following $MA(2)$ process:

$$
X_t = Z_t + \frac{5}{6} Z_{t-1} + \frac{1}{6} Z_{t-2}
$$
Then, we can use invertibility to express $Z_t$ in terms of $X_t$:

$$
Z_t = \beta(B)^{-1} X_t
$$

Where:

$$
\beta(B) = 1 + \frac{5}{6} B + \frac{1}{6} B²
$$

To do so, we must ensure the roots of $\beta$ all lie outside the unit circle. We have the following quadratic equation:

$$
1 + \frac{5}{6} x + \frac{1}{6} x² = 0
$$

Roots of these equations are $x_1=2$ and $x_2=3$. In these case, roots are scalars (may be complex numbers as well) and lie outside the unit circle, so invertibility is assured.

We can invert the moving average process to concert it into an infinite autoregressive process. First, let's compute $\beta(B)^{-1}$:

$$
\beta(B)^{-1} = \frac{1}{1 + \frac{1}{5} B + \frac{1}{6} B^2} = \frac{3}{1+ \frac{1}{2} B} - \frac{2}{1 + \frac{1}{3} B}
$$

Note we can expand this using partial fractions. Each of the fractions can be also expanded into geometric series given $r = - \frac{1}{2} B$ in the first fraction and $r = - \frac{1}{3} B$ in the second fraction. Then, we can write the inverted function as an infinite sum:

$$
\beta(B)^{-1} = \sum^{\infty}_{k=0} 3\left(-\frac{1}{2}B\right)^k - 2 \left(-\frac{1}{3}B\right)^k \\
\beta(B)^{-1} = \sum^{\infty}_{k=0} \left[3\left(-\frac{1}{2}\right)^k - 2 \left(-\frac{1}{3}\right)^k \right] B^k
$$

Then, we can rewrite $Z_t$ as:

$$
Z_t = \beta(B)^{-1} X_t \\
Z_t = \sum^{\infty}_{k=1} \left[3\left(-\frac{1}{2}\right)^k - 2 \left(-\frac{1}{3}\right)^k \right] B^k X_t \\
Z_t = \sum^{\infty}_{k=1} \pi_k B^k X_t = \sum^{\infty}_{k=1} \pi_k X_{t-k}
$$
We see that we have expressed the inventions of the moving average of order $2$ as an autoregressive process of infinite order process through invertibility, when invertibility conditions are satisfied.

## Stationarity for AR(p) processes

Though **moving averages are always stationary, autoregressive functions are not**. Given an autoregressive process of order $p$:

$$
AR(p): \ \ \ \ X_t = Z_t + \phi_1 X_{t-1} + \phi_2 X_{t-2} + \ ... \ + \phi_p X_{t-p}
$$

It can be re-written as:

$$
X_t - \phi_1 X_{t-1} - \phi_2 X_{t-2} - ... - \theta_p X_{t-p} = Z_t \\
(1 - \phi_1 B - \phi_2 B ^2 - \ ... \ - \phi_p B^p) X_t = Z_t \\
\phi(B) X_t = Z_t
$$
In order for $AR(p)$ to be stationary, we need to accomplish similar conditions as the ones seen for invertibility. More precisely, **for (weakly) stationarity, the roots of the polynomial $\phi(B)$ must lie outside the unit circle**, where B is regarded as a complex variable instead of an operator. Recall that $\phi(B)$ is:

$$
\phi(B) = 1 - \phi_1 B - \phi_2 B ^2 - \ ... \ - \phi_p B^p
$$

### Example: AR(1)

Given:

$$
X_t = \phi_1 X_{t-1} + Z_t \implies (1-\phi_1 B) X_t = Z_t \\
\phi(B) = (1-\phi_1 B)
$$

If we try to find the roots of $\phi(B)$:

$$
\phi(x) = 1 - \phi_1 x \implies x = \frac{1}{\phi_1}
$$
Then:

$$
|x| = |\frac{1}{\phi_1}| > 1 \implies |\phi_1| < 1
$$
To ensure root of $\phi(B)$ lies outside the unit circle we must use a $\phi_1$ whose absolute value is smaller than one. When that happens, $AR(1)$ is stationary.

### Variance of AR(1)

If we take the $AR(1)$ from previous subsection, we can rewrite $X_t$ as:

$$
(1-\phi_1 B) X_t = Z_t \implies X_t = (1 - \phi_1 B)^{-1} Z_t \\\\
X_t = \frac{1}{1 - \phi_1B} Z_t = \sum^{\infty}_{k=1} (\phi_1B)^k Z_t = \sum^{\infty}_{k=1} \phi_1^k Z_{t-k}
$$

Note that we have rewritten an autoregressive process of order $p$ into a moving average of infinite order. Then, variance can be computed as:

$$
Var[X_t] = Var \left[\sum^{\infty}_{k=1} \phi_1^k Z_{t-k} \right]  = \sum^{\infty}_{k=1} Var \left[\phi_1^k Z_{t-k} \right]
$$

Since, per definiton:

- $Var [(\phi_1^k Z_{t-k})] = \phi_1^{2k} Var[Z_{t-k}]$
- $Var[Z_t] = \sigma_Z^2$

Then:

$$
Var[X_t] = \sum^{\infty}_{k=1} \phi_1^{2k} \sigma_Z^2 = \sigma_Z^2 \sum^{\infty}_{k=1} \phi_1^{2k}
$$

The summation $\sum^{\infty}_{k=1} \phi_1^{2k}$ is a geometric series that converges if:

$$r = |\phi_1^2| < 1 \implies |\phi_1| < 1$$

Therefore, the variance is finite and does not depend on time.

## Relate MA and AR processes through duality

- Under invertibility conditions of $MA(q)$:

$$ MA(q) \implies AR(\infty) $$

- Under stationarity conditions of $AR(p)$:

$$ AR(p) \implies MA(\infty) $$

In other words:

- Moving average processes of order $q$ can be converted into autoregressive processes of infinte order if the moving average process is under invertibility conditions.
- An autoregressive process of order $p$ can be converted into a moving average of infinite order when the autoregressive process is stationary.